#!/bin/bash
# /usr/local/sbin/ovirt-engine-hostname-sso

/usr/bin/echo "SSO_ALTERNATE_ENGINE_FQDNS=\"$(hostname -f) $(hostname) rhvm.example.com\"" > /etc/ovirt-engine/engine.conf.d/99-custom-sso-setup.conf

