:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

== Red Hat Solutions: IT Optimization - Infrastructure Migration


== Advanced and Experimental exercices

These are excercises that can break the environment.

=== CloudForms Automate Namespace for Migration/IMS

The Automate portion of the IMS tooling ships with the default ManageIQ domain and is located under the namespace:
**/ManageIQ/Transformation**

This section provides an overview of the IMS workflows integrated into CloudForms' Automate domains.  The State Machines and methods in the ManageIQ domain can be copied to a custom Automate domain and modified to modify the behavior of the migration workflows.  This information is provided with the expectation that the reader has a basic knowledge of Automate and its associated syntax.  For those of you without knowledge of Automate, a good primer is available [here](https://manageiq.gitbook.io/mastering-cloudforms-automation-addendum/preface).

Certain aspects of the IMS tooling and workflows are hard-coded and not available to be customized within automate - for example, the methods which parse a migration plan into individual VM migration tasks and the methods which assign a conversion host to a migration task object.

The following sections represent a serialization of the migration process defined within Automate - in reality the process is dynamic.

==== Validation Entry Point State Machine
 
**/Transformation/StateMachines/TransformationPlanRequestApproval/Default**  

A State machine which sets (by default) "approval_type" to "auto" then executes the methods "**validate_request**" and "**approve_request**"

- Ruby method "**validate_request**" essentially executes: `$evm.root['miq_request'].validate_conversion_hosts` 
 If the method returns "true" then the request is validated.
- Ruby method "**approve_request**" sets the request approved as long as the value of "approval_type" is "auto".

  

==== Migration Entry Point State Machine

**/Transformation/StateMachines/VMTransformation/Transformation**

Attributes:

 - **state_machine_phase**: *transformation*
 This attribute is used to determine whether the migration is still in progress.  If any of the migration state machines result in failure, this value is changed to "cleanup".

 - **cleanup_state_machine**: */Transformation/StateMachines/VMTransformation/TransformationCleanup*
 The value set here is used by the /System/CommonMethods/MiqAe/**WeightedUpdateStatus** method to create a cleanup request in the event of a state machine failure.  The WeightedUpdateStatus method is used as the "On Entry", "On Exit" and "On Error" methods for the majority of state machines in this workflow.



States:

- **State2**: _/Transformation/Common/_**AssessTransformation** +
This state is a **Ruby method** which checks the power state of the source VM, sets the options for collapsing snapshots and powering the VM off as well as the check intervals for migration and power off.

- **State5**: _/Transformation/Common/_**AcquireTransformationHost** + 
This state is a **Ruby method** which checks to see if the Transformation request has a conversion host set and sets ae_result to retry if not. (Conversion hosts are set on the request internally)


- **State8**: _/Transformation/StateMachines/VMTransformation_/**PreTransform**_?state_ancestry=${#state_ancestry}/${#ae_state}_ +
This is a **State Machine** with the following:

  * **State2**: _/Transformation/StateMachines/Ansible/_**TransformationPlaybook**_?transformation_hook=pre_ +
This is a **State Machine** With The Following:

    ** **State2**: _/Transformation/Ansible/_**LaunchPlaybookAsAService**_?transformation_hook=${#transformation_hook}_ +
This is a **Ruby method** which checks the migration request for a "pre" migration playbook and executes it as a CloudForms Service with the source VM as its target.

    ** **State5**: _/Transformation/Ansible/_**CheckPlaybookAsAService**_?transformation_hook=${#transformation_hook}_ +
This is a **Ruby method** which checks to see if a playbook-as-a-service has been instantiated as part of the migration request and checks its status. If the status shows the playbook has not completed or errored out, the state is re-tried at a fixed interval (15 seconds)

   * **State5**: _/Transformation/Infrastructure/VM/Common/_**PowerOff** +
This is a **Ruby method** which issues the command to power off a VM if the VM is not already powered off and the option is set to power it off (The option set by the **AssessTransformation** method). The method sets a state var if a shutdown has been requested and continues to retry the state until the VM is shut down or the retries (set to 10 within the method) are exhausted.

   * **State8**: _/Transformation/Infrastructure/VM/Common/_**CollapseSnapshots** +
This is a **Ruby method** which issues the command to collapse VM snapshots if the option is set (by the AssessTransformation method).

   - **State11**: _/Transformation/StateMachines/VMTransformation/_**Transform**_?state_ancestry=${#state_ancestry}/${#ae_state}_ +
This is a **State Machine** with the following:

     * **State2**: _/Transformation/Common/_**VMTransform** +
This is a **Ruby method** which executes the "run_conversion" internal method for the conversion task. It also includes a commented-out-by-default debug string which will write the "conversion_options" hash to the log.

     * **State5**: _/Transformation/Common/_**VMCheckTransformed** +
This is a **Ruby method** which evaluates the status of a migration and updated the percentage completed based on the percentage of the source disks which have been copied. This method will retry until it succeeds or fails.

     * **State8**: _/Transformation/Infrastructure/VM/Common/_**CheckVmInInventory** +
This is a **Ruby method** which checks the target provider's inventory for the presence of the target VM (by name). It will retry every 15 seconds until the VM appears in inventory.

     - **State14**: _/Transformation/StateMachines/VMTransformation/_**PostTransform**_?state_ancestry=${#state_ancestry}/${#ae_state}_ +
This is a **State Machine** with the following:

       * **State2**: _/Transformation/Infrastructure/VM/Common/_**ApplyRightSize** +
This feature is not currently used. It is a **Ruby method** which checks the conversion request for options named "right_size_strategy_cpu" and "right_size_stragegy_memory" on the conversion request. If present the destination VM's vCPU and memory will be set to the "recommended" values.

       * **State5**: _/Transformation/Infrastructure/VM/Common/_**SetDescription** +
This is a **Ruby method** which sets the description field of the VM on the destination provider (RHV, OSP) to "Migrated by Cloudfoms on MMDDYY".

       * **State8**: _/Transformation/Infrastructure/VM/Common/_**PowerOn** +
This is a **Ruby method** which checks the value of the conversion task option "source_vm_power_state". If the VM is supposed to be powered on, it issues a "start" command. If the "transformation_phase" is set to "transform" the target VM is started, if it is set to "cleanup" (indicating a failed migration) the source VM is started instead. "transformation_phase" is set by the /Transformation/Common/Utils Ruby method which checks the "state_machine_phase" of $evm.root

       * **State11**: _/Transformation/Infrastructure/VM/Common/_**CheckPoweredOn** +
This is a **Ruby method** which checks the power state of the VM. (The Target VM if the state machine phase is "transform" and the source VM if the state machine phase is "cleanup"). It will re-try the state every 15 seconds until the power state shows "on".

       * **State14**: _/Transformation/StateMachines/Ansible/_**TransformationPlaybook**_?transformation_hook=post_ +
This is a **State Machine** With The Following:

         ** **State2**: _/Transformation/Ansible/_**LaunchPlaybookAsAService**_?transformation_hook=${#transformation_hook}_ +
This is a Ruby method which checks the migration request for a "post" migration playbook and executes it as a CloudForms Service with the destination VM as its target.

         ** **State5**: _/Transformation/Ansible/_**CheckPlaybookAsAService**_?transformation_hook=${#transformation_hook}_ +
This is a **Ruby method** which checks to see if a playbook-as-a-service has been instantiated as part of the migration request and checks its status. If the status shows the playbook has not completed or errored out, the state is re-tried at a fixed interval (15 seconds)

       * **State17**: _/Transformation/Infrastructure/VM/Common/_**RestoreVmAttributes** +
This is a **Ruby method** which copies the CloudForms service name, tags, custom_attributes, ownership and retirement data of the source VM to the destination VM. (This is only useful if the source VM was already being managed by the same CloudForms instance used to perform the migration. It does not transfer these attributes to external CloudForms regions, nor does it alter the VMs on the provider(s)).

       * **State20**: _/Transformation/Common/_**SetMigrated** +
This is a **Ruby method** which executes the "mark_vm_migrated" method on the task object.


=== Customizing the Migration Workflow 

In this part of the training you will customize the migration workflow to perform extra steps.
[NOTE]
Before proceeding with customization, export the automate domains from MiQ/CloudForms.

Pick one of the following use-case:

. (easy) Modify automate to add a step in your statemachine to .... (tbd)

. (medium) Ansible pre-migration step:   Use ansible to add the VM name to a log file (tracking VM migrations)

. (hard - bonus point) : Change CPU or Memory configuration of a VM after migration using Ansible or Automate.

=== Customizing Pre and Post Playbooks

TODO: Add pre/post playbooks and how to customize them
