:scrollbar:
:data-uri:
:toc2:

== Red Hat Solutions: IT Optimization - Infrastructure Migration

:numbered:

== Overview

This demonstration uses Red Hat CloudForms as a broker to drive virtual-to-virtual tools such as `ovftool` and `virt-v2v` to migrate VMs from VMware vSphere to Red Hat Enterprise Virtualization 

.Goal
* Migrate the VMs with a Red Hat Solution: IT Optimization - Infrastructure Migration
+
NOTE: The source VM's are still maintained post migration and are not deleted. This allows for "failback" if a migration failure occurs.

.Prerequisites

* Deployment of the demo environment which includes the following provisioned VMs:
** `jboss0` - a Red Hat Enterprise Linux 7 host running JBoss EAP
** `jboss1` - a Red Hat Enterprise Linux 7 host running JBoss EAP
** `nginx` - a Red Hat Enterprise Linux 7 host running Nginx  configured to proxy traffic to `jboss0` and `jboss1`
** `db` - a Red Hat Enterprise Linux 7 host running PostgreSQL that the `jboss0` and `jboss1` application servers connect to

Current versions of products used:

[cols="1,1",options="header"]
|=======
|Product |Version 
|CloudForms |4.5
|Red Hat Virtualization |4.1
|VMware vSphere |5.5
|=======

=== System Requirements

* Firefox 17 or higher
* Chromium (for vCenter and CloudForms connectivity)
+
[NOTE]
Internet Explorer is not recommended.

* Adobe Flash 15 or higher must be enabled in Firefox or Chromium used for vCenter connectivity
* SSH client

=== Environment

A full new demo environment is deployed on every request. To make the environment unique a 4 character identifier is assigned to it (i.e. `1a2b`), this identifier is referred in this documentation as *GUID*.  

The demo environment consists of the following systems:

[cols="1,1,1,2",options="header"]
|=======
| Hostname | Internal IP | External name | Description
|`migration.example.com` | `192.168.0.6` | N/A |Virtual-to-Virtual Migration server
|`workstation.example.com` |`192.168.0.10` | workstation-<YOUR-GUID>.rhpds.opentlc.com |Jump host
|`storage.example.com` |`192.168.0.254` | workstation-<YOUR-GUID>.rhpds.opentlc.com | NFS server
|`cf.example.com` |`192.168.0.100` |  cf-<YOUR-GUID>.rhpds.opentlc.com |CloudForms server
|`kvm.example.com` |`192.168.0.40` | kvm-<YOUR-GUID>.rhpds.opentlc.com |KVM hypervisor managed by Red Hat Enterprise Virtualization
|`rhvm.example.com` |`192.168.0.35` | rhvm-<YOUR-GUID>.rhpds.opentlc.com |Red Hat Enterprise Virtualization Manager server
|`esx1.example.com` |`192.168.0.51` | N/A |ESXi hypervisor
|`esx2.example.com` |`192.168.0.52` | N/A |ESXi hypervisor
|`vcenter.example.com` |`192.168.0.50` | vcenter-<YOUR-GUID>.rhpds.opentlc.com |VMware vCenter server
|=======


=== Obtaining or enabling access credentials

. First time login, forgot login or password? Go to https://www.opentlc.com/account 

. Your username should NOT have an *@* in it. 

. Partners MUST request access to RHPDS by sending an email to open-program@redhat.com. 

=== Provision Your Demo Environment

. Log in to the link:https://rhpds.redhat.com/[Red Hat Product Demo System] with your provided credentials. 

. Go to *Services -> Catalogs*.

. Under *All Services -> Red Hat Solutions*, select *Infrastructure Migration Demo*.

. On the right pane, click *Order*.

. Please, read carefully all of the information on the resulting page, check the box to confirm you understood the runtime warning message, and then click *Submit*.
+
[IMPORTANT]
====
* It takes about 20 ~ 30 minutes for the demo to load completely and become accessible.
** Wait for the full demo to load, even if some of its systems are marked "Up."
* Watch for an email with information about how to access your demo environment.
** Make note of the email's contents: a list of hostnames, IP addresses, and your GUID.
** Whenever you see <YOUR-GUID> in the demo instructions, replace it with the GUID provided in the email.
* You can get real-time updates and status of your demo environment at https://www.opentlc.com/rhpds-status.
====
+
[TIP]
Be mindful of the runtime of your demo environment! It may take several hours to complete the demo, so you may need to extend the runtime. This is especially important in later steps when you are building virtual machines. For information on how to extend runtime and lifetime, see https://www.opentlc.com/lifecycle.

== Getting Started

. Once the system is running, use SSH to access your demo server using your OPENTLC login name and private SSH key.

* Using a Unix/Linux system:
+
----
$ ssh -i /path/to/private_key <YOUR-OpenTLC-USERNAME-redhat.com>@workstation-<YOUR-GUID>.rhpds.opentlc.com
----

* Example for user 'batman' and GUID '1a2b', using the default ssh private key:
+
----
$ ssh -i ~/.ssh/id_rsa batman-redhat.com@workstation-1a2b.rhpds.opentlc.com
----

. Become `root` using the provided password:
+
----
$ sudo -i
----

. Check the status of the environment using ansible:
+
----
# ansible all -m ping
----
+
This command establishes a connection to all the machines in the environment (except ESXi servers). 
In case the machines are up an running a success message, per each, will show up. 
This is an example of a success message for the VM jboss0.example.com:
+
----
jboss0.example.com | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
----
+ 
There are 4 VMs in the vCenter environment hosting an app with Nginx as loadbalancer, two JBoss EAP in domain mode, and a Postgresql database.
To check only if these ones are running, you may use the following command:
+
----
# ansible app -m ping
----

. Establish an SSH connection to the CloudForms server and monitor `automation.log`:
+
----
# ssh cf.example.com
# tail -f /var/www/miq/vmdb/log/automation.log
----
+
[TIP]
The log entries are very long, so it helps if you stretch this window as wide as possible.

. From a web browser, open each of the URLs below in its own window or tab, using these credentials (except when noted):

* *Username*: `admin`
* *Password*: `<to_be_provided>`
+
[NOTE]
You must accept all of the self-signed SSL certificates.

* *Red Hat Enterprise Virtualization Manager:* `https://rhevm-<YOUR-GUID>.rhpds.opentlc.com`
.. Navigate to and click *Administration Portal* and log in using `admin`, `<to_be_provided>`, and `internal`.

* *vCenter:* `https://vcenter-<YOUR-GUID>.rhpds.opentlc.com`

.. Use `root` as the username to log in to vCenter.

.. Click *Log in to vSphere Web Client*.

** Flash Player is required.
+
[TIP]
Modern browsers have flash player disabled by default. You may need to enable it for this page.

.. Click *VMs and Templates*.

* *CloudForms:* `https://cf-<YOUR-GUID>.rhpds.opentlc.com`

+
[NOTE]
If you are accessing the Satellite console, you may see `error` for the Satellite server's status and `out-of sync` for the hosts' statuses. This is normal and can be ignored.
+
[TIP]
You can also find these URLs in the email provided when you provisioned the demo environment.

=== Validate the Current VMs

. On the CloudForms web interface, go to *Compute -> Infrastructure -> Providers*.

. If you see an exclamation mark (*!*), or a cross (*x*) in a provider, check the provider's box, go to *Authentication -> Re-check Authentication Status*.
+
[TIP]
Take into account that vCenter may take longer to start.

. Go to *Compute -> Infrastructure -> Virtual Machines -> VMs -> All VMs*.

. All VMs and Templates in both RHV and vSphere show as entities in CloudForms.
+
[NOTE]
If you needed to validate providers, you may have to wait a few minutes and refresh the screen before the VMs show up.

. Select the pane *VMs & Templates* and, in it, the *VMware* provider.

. Only the VMs and Templates in vSphere will show.

. Use CloudForms to shut down (_not_ power off) all four VMs (db, jboss0, jboss1, nginx).
+
[TIP]
You may verify that VMs are down by running in the terminal in the workstation machine the check command:
----
# ansible app -m ping
----

== Migrate the db (PostgreSQL) VM from VMware to Red Hat Virtualization

=== Configure Red Hat Enterprise Virtualization as a Migration Destination

. On the `cf` system, go to *Infrastructure -> Providers*.

. Click *RHV*.

. Select *Policy -> Edit Tags*.

. Select *Point of Arrival* and then select *Rhev* for the assigned value.
+
* This sets this provider as an available Red Hat Enterprise Virtualization destination.

. Select the *provider_type* tag and select *POA* for the assigned value, then click *Save*.
+
* This sets this provider as the current point of arrival.

=== Configure VMware as a Migration Source

. Navigate to the *VMware* provider.

. Select *Policy -> Edit Tags*.

. Select *provider_type* and select *POD* for the assigned value, then click *Save*.
+
* This sets this provider as the point of departure or source provider.

=== Set VM Migration Attributes

. On the `cf` system, go to *Services -> Catalogs -> Service Catalogs*.

. Under *All Services -> Import CSV*, select *Import Attributes*.

. On the right, click *Order*.

. On the resulting screen, enter `attributes.csv` in the *Filename* field and click *Submit*.

. Monitor `automation.log` on the `cf` server.  When the process is complete, continue with the next section.
+
[NOTE]
If you see any errors about `wp2-rhcs-example-com`, you can ignore them for now because you are not exporting from Red Hat Enterprise Virtualization yet.

=== Set VM Migration Tags

. On the `cf` system, go to *Services -> Catalogs -> Service Catalogs*.

. Under *All Services -> Import CSV*, select *Import Tags*.

. On the right, click *Order*.

. On the resulting screen, enter `tags.csv` in the *Filename* field and click *Submit*.

. Monitor `automation.log` on the `cf` server.  When the process is complete, continue with the next section.
+
[NOTE]
Continue to ignore errors about `wp2-rhcs-example-com`.

=== Check Tags and Attributes

. Go to *Infrastructure -> Providers -> Virtual Machines -> VMs -> All VMs*.

. Navigate to the `mysql` VM.

. Under *Custom Attributes*, confirm that there is a custom attribute called `ip` with the value you provided in `attributes.csv`.

. Under *Smart Management*, confirm that *migrate_group* is set to `demo1` and *Point of Arrival* is set to `Rhev`.

=== Start VM Migration

. On the `cf` system, go to *Services -> Catalogs -> Service Catalogs*.

. Under *All Services -> Migration*, select *Batch_Migrate*.

. On the right, click *Order*.

. For *Migration Group*, select `demo1` and click *Submit*.

. Monitor `automation.log` and the Red Hat Enterprise Virtualization Admin GUI closely.
+
[TIP]
====
It may be beneficial to open three separate sessions to the Migration server and run the following:

----
# watch find /mnt
----

----
# tail -f /mnt/migrate/ova/mysql.rhcs.example.com/*log
----

----
# tail -f /mnt/migrate/ova/mysql.rhcs.example.com/*err
----
====
+
NOTE: It takes about 20 minutes for `automation.log` to show that the service is complete.

=== Verify VM Migration

. Log in to the Red Hat Enterprise Virtualization Admin GUI and open the console for the `mysql` VM that was migrated.

. Start the `mysql` VM and log in as `root` with the password `<to_be_provided>`.

. Make sure the VM retained the IP address from `attributes.csv` and that it can resolve an external hostname.


== Migrate the wp1 VM from VMware to RHV Platform

=== Configure RHV Platform as a Migration Destination

. On the `cf` system, go to *Clouds -> Providers*.

. Select *OSP*.

. Select *Policy -> Edit Tags*.

. Select *Point of Arrival* and select *RHV* for the assigned value.
+
* This sets this provider as an available *RHV* destination.

. Select *provider_type* and select *POA* for the assigned value, then click *Save*.
+
* This sets this provider as the current point of arrival.

=== Clear the POA Tag from Red Hat Enterprise Virtualization

. On the `cf` system, go to *Infrastructure -> Providers*.

. Select *RHV*.

. Select *Policy -> Edit Tags*.

. Click the *Trash Can* icon next to the Point of Arrival tag.

. Click the *Trash Can* icon next to the provider_type tag.

. Click *Save*.

. Set the VM tags and attributes. 
+
NOTE: Anytime a change is made to the either the tags or attributes .csv files, the *Import Tags* and *Import Attributes* catalog items must be run again.  The same goes for making changes to the *POA* and *POD* tags for providers.

. Using the procedure learned before, monitor `automation.log` while running the *Import Tags* and *Import Attributes* catalog items again.
+
[NOTE]
You can ignore the warnings from the VMs with disabled providers.

=== Migrate the VM

. On the `cf` system, go to *Services* -> *Catalogs* -> *Service Catalogs*.

. Under *All Services -> Migration*, select *Batch_Migrate*.

. On the right, click *Order*.

. For *Migration Group*, select `demo2` then click *Submit*.

. Monitor `automation.log` and the RHV Platform dashboard closely.


== Migrate the wp2 VM from Red Hat Enterprise Virtualization to RHV Platform

=== Clear the POD Tag from VMware

. On the `cf` system, go to *Infrastructure -> Providers*.

. Select *VMware*.

. Select *Policy -> Edit Tags*.

. Click the *Trash Can* icon next to the Point of Arrival tag.

. Click the *Trash Can* icon next to the provider_type tag.

. Click *Save*.

=== Configure Red Hat Enterprise Virtualization as a POD

. Navigate to the *RHV* provider.

. Click *Policy -> Edit Tags*.

. Select the *provider_type* tag, select *POD* for the assigned value, and then click *Save*.

. Set the VM tags and attributes
+
NOTE: Anytime a change is made to the either the tags or attributes .csv files, the *Import Tags* and *Import Attributes* catalog items must be run again.  The same goes for making changes to the *POA* and *POD* tags for providers.

.. Using the procedure learned before, monitor `automation.log` while running the *Import Tags* and *Import Attributes* catalog items again.
+
[NOTE]
You can ignore the warnings from the VMs with disabled providers.

=== Migrate the VM

. On the `cf` system, go to *Services -> Catalogs -> Service Catalogs*.

. Under *All Services -> Migration*, select *Batch_Migrate*.

. On the right, click *Order*.

. For *Migration Group*, select `demo3` then click *Submit*.

. Monitor `automation.log` and the RHV Platform dashboard closely.

== End State

* You now have the `mysql` server on Red Hat Enterprise Virtualization and the two `wp` servers on RHV Platform.  
* The `haproxy` system remains on Red Hat Enterprise Virtualization.

== Extra Credit

* Use what you learned in this lab to migrate `haproxy` to RHV Platform.
