:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

== Red Hat Solutions: IT Optimization - Infrastructure Migration

== Troubleshooting the Migration Solution

=== Network Communication
. If network communication is severed between the source and target providers during migration, the migration will fail.  If the VM migration has begun import into the export domain in RHV, the faile dmigration will need to be cleaned up before attempting migration post failure.

=== Logs 
. The conversion log is stored in /tmp on conversion host.
+
[NOTE]
On earlier conversion host configurations, logs can be found in /var/log/vdsm/import/
+
. On the MiQ/CloudForms appliance, logs are located under /var/www/miq/vmdb/log/automation.log

=== Processes
. Infrastructure Migration uses virt-v2v to perform VM migrations from source to target.  This process runs on the RHV conversion host and is part of virt-v2v-wrapper.py.  https://github.com/oVirt/ovirt-ansible-v2v-conversion-host/blob/master/files/virt-v2v-wrapper.py

.. The launch of virt-v2v-wrapper.py is done through SSH, directly from CloudForms, using the net-ssh gem. The wrapper input is passed as standard input through the SSH channel and the output is collected. The wrapper immediately returns, so the SSH connection is short and less prone to network issues.

.. Currently, CloudForms leverages the host credentials, that have to be provided through the WebUI: Infrastructure > Hosts > Configuration > Edit this host. These credentials are used to initiate the SSH channel. We use the root user account, as it is required to run the wrapper.

=== Common Failures
. Incorrect infrastructure mappings
. RHV host credentials not set in MiQ/CloudForms
. Incorrect attributes for import .csv file


